### ISSUE TITLE
Repeatable field in Backpack - how to add validation to subfields

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/blog-articles#14]
Definitely possible, inside the regular FormRequest, but more difficult than usual. As such, a tutorial would probably be good, so it's easy to understand and/or copy-paste.

**Comment by tabacitu** [comment]
Update: I've recently added some example code inside the Demo, for at least provide some kind of start for people to have validation to the repeatable fields & subfields. Check out [`DummyRequest.php`](https://github.com/Laravel-Backpack/demo/blob/master/app/Http/Requests/DummyRequest.php#L31-L61)

**Comment by Dalia-Gerguis** [comment]
Thank you!

**Comment by tabacitu** [comment]
Heads-up @Dalia-Gerguis , in Backpack v5 validation for the `repeatable` is no longer tricky! You just use Laravel's [nested array validation](https://laravel.com/docs/8.x/validation#validating-nested-array-input). You'll notice that inside the repeatable docs too: https://backpackforlaravel.com/docs/5.x/crud-fields#repeatable-pro

Soo... I'm going to close this issue, it's no longer worth writing about, I think. Since it's no longer complicated.

Cheers!
