### ISSUE TITLE
Charts for your backpack dashboard

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/blog-articles#9]
![output](https://user-images.githubusercontent.com/4065733/51219025-89882a80-18f4-11e9-9a22-cc7703358ee3.gif)

Topics: 

- Creating json routes in your dashboard
- Planning the query in SQL and building json
- Integrating the library chart.js the easy way
- Building the interface

Bonus: 
- Adding buttons to change date range

**Comment by tabacitu** [comment]
LOVE IT! Line/bar + pie chart should be enough to cover most use cases - most information can be shown using one of those.

Let's see what others think about the idea, but I think this will be of interest to many. I think Backpack can pay for a good tutorial on this subject.

**Comment by mediaworkbench** [comment]
this is exactly what i am looking for! has anybody done it yet? is there resources i can dig? any help appreciated!

**Comment by tabacitu** [comment]
@eduardoarandah , @mediaworkbench - I've just introduced widgets for v4 - it should make it A LOT easier to do this. I haven't created the widgets for line/bar/pie charts yet, only simpler ones, but they're on the roadmap. PR is here - https://github.com/Laravel-Backpack/Base/pull/390 . If you have the time, let me know what you think about the implementation.

**Comment by FreddyCrugger** [comment]
will the charts still be implemented in backpack 4 please? Thank you.

**Comment by tabacitu** [comment]
Good news everyone! 🎉 🎈 Backpack 4.1 has a pretty cool "chart" widget, so the docs should eliminate the need for this article. If you're interested in Charts in Backpack, check out its [docs here](https://backpackforlaravel.com/docs/4.1/base-widgets#chart). I think I've made it dead-simple to have charts inside Backpack, and with AJAX-loaded data no less.

Full disclosure: I'm trying to get people excited about Backpack 4.1, so that they install the beta, so that we have it tested with other real-life projects too 😁 ...is it working? 🙄

**Comment by tabacitu** [comment]
Hmmm... one thing that chart widget does _not_ have - buttons to change the timeframe like @eduardoarandah 's has above... which would be really cool and useful to have...

**Comment by alancwoo** [comment]
@tabacitu I'm using backpack for the first time, so pardon my ignorance. I started with stable and found this issue trying to setup a chart on the dashboard. I updated to `4.1.x-dev` - the upgrade guide was very clear, but also since I'm just starting out, it wasn't very hard.

My question is (more likely related to a lack of overall familiarity): [The docs](https://backpackforlaravel.com/docs/4.1/base-widgets#chart) state:

> Step 3. Add the widget that points to that ChartController you just created:

```
Widget::add([ 
    'type' => 'chart',
    'controller' => \App\Http\Controllers\Admin\Charts\WeeklyUsersChartController::class
    ...
```

I'm just a bit confused where to put this. I put it in the chart controller itself but don't see anything reflected in the dashboard. (Actually I was also confused that `dashboard.blade.php` didn't exist, so I built one like so:

```
@extends(backpack_view('blank'))

@php
    $widgets['before_content'][] = [];
@endphp

@section('content')
@endsection
```

**Comment by alancwoo** [comment]
Ok! It is as simple as:

`dashboard.blade.php`

```
@php
    $widgets['before_content'][] = [
        'type'        => 'chart',
        'controller' => \App\Http\Controllers\Admin\Charts\WeeklyUsersChartController::class,
    ];
@endphp
```
But out of curiosity, where would one call the `Widget::add...` typically?

**Comment by tabacitu** [comment]
Well that's the thing. You can call it anywhere 😄 

Personally I prefer to call it inside the controller. So it'd be either inside the `setupXxxOperation()` method of a CrudController (if I want to add a widget to a particular CRUD operation, like Show or List), or inside a custom controller like AdminController (for the dashboard).

Hope it helps.

**Comment by alancwoo** [comment]
Thank you @tabacitu - I'm very impressed with everything so far and have bought a license, thanks for this wonderful software :) I can say so far 4.1 is working quite well for my somewhat basic build so far!

**Comment by srigurubyo** [comment]
Hi @alancwoo 

Actually I am experiencing the same problem. I am not having file `dashboard.blade.php`. I just want to know how you generated this file. Can you please share the steps required for generating it.

**Comment by srigurubyo** [comment]
Hi @alancwoo 
Actually I am experiencing the same problem. I am not having file `dashboard.blade.php`. I just want to know how you generated this file. Can you please share the steps required for generating it.

**Comment by mbc-audiovisuales** [comment]
Hi, I would like to know if there is any way to pass parameters to controller when adding a Widget, like

`Widget::add([ 
    'type'       => 'chart',
    'controller' => \App\Http\Controllers\Admin\Charts\Poll\PollVotingChartController::class,
    'args' => ['poll_id' => 35],

    // OPTIONALS

    // 'class'   => 'card mb-2',
    // 'wrapper' => ['class'=> 'col-md-6'] ,
    // 'content' => [
         // 'header' => 'New Users', 
         // 'body'   => 'This chart should make it obvious how many new users have signed up in the past 7 days.<br><br>',
    // ],
]);`

Thanks!

**Comment by mbc-audiovisuales** [comment]
> Hi, I would like to know if there is any way to pass parameters to controller when adding a Widget, like
> 
> ```
> Widget::add([ 
>     'type'       => 'chart',
>     'controller' => \App\Http\Controllers\Admin\Charts\Poll\PollVotingChartController::class,
>     'args' => ['poll_id' => 35],
> 
>     // OPTIONALS
> 
>     // 'class'   => 'card mb-2',
>     // 'wrapper' => ['class'=> 'col-md-6'] ,
>     // 'content' => [
>          // 'header' => 'New Users', 
>          // 'body'   => 'This chart should make it obvious how many new users have signed up in the past 7 days.<br><br>',
>     // ],
> ]);
> ```
> 
> Thanks!

I just found that extgending chart.blade.php I can make it. Thanks anyway!

**Comment by mbc-audiovisuales** [comment]
> > Hi, I would like to know if there is any way to pass parameters to controller when adding a Widget, like
> > ```
> > Widget::add([ 
> >     'type'       => 'chart',
> >     'controller' => \App\Http\Controllers\Admin\Charts\Poll\PollVotingChartController::class,
> >     'args' => ['poll_id' => 35],
> > 
> >     // OPTIONALS
> > 
> >     // 'class'   => 'card mb-2',
> >     // 'wrapper' => ['class'=> 'col-md-6'] ,
> >     // 'content' => [
> >          // 'header' => 'New Users', 
> >          // 'body'   => 'This chart should make it obvious how many new users have signed up in the past 7 days.<br><br>',
> >     // ],
> > ]);
> > ```
> > 
> > 
> > Thanks!
> 
> I just found that extgending chart.blade.php I can make it. Thanks anyway!

For the record i just redefined chart.blade.php with slightly changing how controller is invoked at the beginning:

```
@php
  // -----------------------
  // Backpack ChartJS Widget
  // -----------------------
  // Uses:
  // - Backpack\CRUD\app\Http\Controllers\ChartController
  // - https://github.com/ConsoleTVs/Charts
  // - https://github.com/chartjs/Chart.js

  $constructorParameters = $widget['constructor'];
  $controller;
// If widget lacks custom by-name defined controller, follow default controller invoke method
if(empty($widget['controller_name'])){
    $controller = new $widget['controller'];
// If widget defined by controller_name as string denoting controller full class path, follow custom invoking code with added args
  } else {
    $controllerName = $widget['controller_name'];
    $r = new ReflectionClass($controllerName);
    $controller = $r->newInstanceArgs(($constructorParameters['arg'] ?? []));
  }
...
```


Widget is declared with these options:

```
[ 
	    'type'       => 'chart',
	    'controller_name' => '\path\to\controller\MyChartController',
	    'constructor' => [ 'arg' => [$valueToPassAsArgument] ],
	]
```

Created my own chart controller base class, extended by chart controller classes later, similar to default chart controller class by backpack, with a custom constructor:


 ```
class BaseChartControllerClass {
   public function __construct($arg = null)
    {
        // Pass to custom setup method the parameter
        $this->setup($arg);
        $this->setLibraryFilePathFromDatasetType($this->chart->dataset);
    }
```

And in chart controller class, classes extending that base class, declaring custom setup function

```
class ChartControllerClass extends BaseChartControllerClass {
    public function setup($arg)
    {
        $this->arg= $arg;
        $this->chart = new ChartControllerClass();
        $this->chart->load(backpack_url('charts/poll/poll-voting/'.$this->arg));
    }
```

with of course declaring route to the controller at custom.php


`    Route::get('charts/route/action/{arg}', 'path\to\BaseChartControllerClass@response')->name('charts.route/action.index');`

Hope it helps !!

**Comment by tabacitu** [comment]
I think it's an excellent idea @mbc-audiovisuales . Thanks a lot for sharing this with everyone. I've [opened an issue](https://github.com/Laravel-Backpack/CRUD/issues/3287) to maybe introduce something like this for everyone, so that in the future you don't need to overwrite anything to achieve the same thing. Let me know what you think about it in https://github.com/Laravel-Backpack/CRUD/issues/3287

Cheers!

**Comment by hasanakhtar** [comment]
Hi,

The charts widget is not working in Backpack 5 Pro+ Laravel 9 for me.  
Following the steps in the doc (https://backpackforlaravel.com/docs/5.x/base-widgets#chart-pro).
1-Installed the Chart Library
2- Created the Chart controller and added a chart. Can see the jason at route: "admin/charts/weekly-users"
3- Added the widget in the dashboard blade page

The Dashboard page is emitting @loadScriptOnce($path) right at the bottom of the page.....and the console is saying "Chart is not defined"

**Comment by Kistlak** [comment]
is anyone know how can we rerender charts using ajax ?? I searched, but no enough docs.

**Comment by tabacitu** [comment]
@Kistlak check out [the docs for the Chart widget](https://backpackforlaravel.com/docs/5.x/base-widgets#chart-pro). The first example explains how to add AJAX-loaded charts.

**Comment by Kistlak** [comment]
@tabacitu yes, I did the exact same thing. but, I can't figure out how to rerender the chart without reloading the page using ajax or any other method..
